### ISSUE TITLE
Problem with installing with Laravel 5

### ISSUE THREAD

**Issue by pascallammers** [Braunson/laravel-html5-forms#6]
Hey,

I get this error message when trying to install it with Laravel 5 setup.

`Installation request for laravel/framework == 5.0.2.0 -> satisfiable by laravel/framework[v5.0.2].
`

Regards

**Comment by Braunson** [comment]
There's no tagged version yet for L5, I will look into updating it for L5 soon.

**Comment by pascallammers** [comment]
Ok, I just copied the last line out of the error message sorry

`Problem 1
    - Installation request for braunson/laravel-html5-forms dev-master -> satisfiable by braunson/laravel-html5-forms[dev-master].
    - Conclusion: remove laravel/framework v5.0.4
    - braunson/laravel-html5-forms dev-master requires illuminate/support 4.2.* -> satisfiable by illuminate/support[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - don't install illuminate/support v4.2.1|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.12|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.16|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.17|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.2|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.3|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.4|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.5|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.6|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.7|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.8|don't install laravel/framework v5.0.4
    - don't install illuminate/support v4.2.9|don't install laravel/framework v5.0.4
    - Installation request for laravel/framework == 5.0.4.0 -> satisfiable by laravel/framework[v5.0.4].
`

This is the full "error" message when I´m trying the `composer require "braunson/laravel-html5-forms:dev-master"` script.

Thanks for the fast feedback!
Regards

**Comment by Braunson** [comment]
@pascallammers I've updated composer's requirement for illuminate/support to work with Laravel 5 but have yet to test the script in Laravel 5.

**The branch is here:**
https://github.com/Braunson/laravel-html5-forms/tree/laravel-5

**Try running:**
```
composer require "braunson/laravel-html5-forms:dev-laravel-5"
```

**Comment by pascallammers** [comment]
That worked like a charm - Thanks!
