### ISSUE TITLE
Why did you remove the master (L4) branch from packagist? 

### ISSUE THREAD

**Issue by jonasva** [Braunson/laravel-html5-forms#9]
I was migrating an old Laravel 4 project depending on your bundle, but got constraint issues with it not being able to find the dev-master branch. I went to check, and it's indeed gone from packagist. Is it possible to put it back, or to make a separate Laravel 4 branch?

**Comment by Braunson** [comment]
https://github.com/Braunson/laravel-html5-forms/releases/tag/4.0
